### ISSUE TITLE
Comparing two arrays in componentWillReceiveProps??

### ISSUE THREAD

**Issue by saher-elgendy** [jeffersonRibeiro/react-shopping-cart#10]
I am confused about that part

```
componentWillReceiveProps(nextProps) {
    const { filters: nextFilters, sort: nextSort } = nextProps;

    if (nextFilters !== this.props.filters) {
      this.handleFetchProducts(nextFilters, undefined);
    }
  }
```

You are comparing two arrays which always will return false and this would make your condition always true
`[1, 2] === [1, 2] // false`

Don't you think that it's a bad behaviour in your code???

**Comment by jeffersonRibeiro** [comment]
Haha Thanks! I will review the code and change it, you are totally right.

**Comment by Syed-Saad-Qamar** [comment]
PR https://github.com/jeffersonRibeiro/react-shopping-cart/pull/22 credit goes to @saher-elgendy

**Comment by saher-elgendy** [comment]
@Syed-Saad-Qamar i think every thing is fine now because of your fix .

**Comment by SaadQamar01** [comment]
@saher-elgendy Thanks for your kindness, yeah definitely we can use **useEffect** but the entire project I don't see they are using **hooks **, you can create a separate issue for **hooks** so I will raise a PR for that.
@jeffersonRibeiro could you please **review** and if there is no issue found **merge** it.

Thanks

**Comment by jeffersonRibeiro** [comment]
Thanks @saher-elgendy and @Syed-Saad-Qamar !

**Comment by jeffersonRibeiro** [comment]
@all-contributors please add @Syed-Saad-Qamar  for code

**Comment by jeffersonRibeiro** [comment]
@all-contributors please add @saher-elgendy  for bug
