### ISSUE TITLE
redundant mapStateToProps in Filter component

### ISSUE THREAD

**Issue by saher-elgendy** [jeffersonRibeiro/react-shopping-cart#11]
I think this part is redundant as you did not use filters props in the component

```
const mapStateToProps = state => ({
  filters: state.filters.items
});

export default connect(
  mapStateToProps,
  { updateFilters }
)(Filter);

```
I think the first argument of ```connect``` should be ```null```, or you may have an explanation for this!!

**Comment by jeffersonRibeiro** [comment]
Hi @saher-elgendy ! Thank you for pointing that out, when I got time I will fix.

If you wish to send a PR I will kindly accept.

**Comment by Syed-Saad-Qamar** [comment]
PR credit goes to @saher-elgendy
