### ISSUE TITLE
Is there a tutorial?

### ISSUE THREAD

**Issue by nhoktenz** [jeffersonRibeiro/react-shopping-cart#13]
I am wondering if there is a tutorial somewhere for this. This is so cool. Thanks

**Comment by dvachhani** [comment]
lol

**Comment by dvachhani** [comment]
You're welcome

**Comment by Curti-s** [comment]
Please we would really like a tutorial or rather an overview of how the project was created. Thanks.

**Comment by jeffersonRibeiro** [comment]
I'm talking to some people to help me record a step by step on how this project was created.
All about React principles, folder structure, testing and CI/CD.

The problem is that I need someone who can speak english to help me record.

**Comment by Muheet707** [comment]
Hey, If possible please upload a tutorial somewhere which describes how the project was created.

**Comment by jeffersonRibeiro** [comment]
@all-contributors please add @nhoktenz  for idea

**Comment by jeffersonRibeiro** [comment]
@all-contributors please add @criesbeck for idea, tutorial, content, review and bug

**Comment by ExReal** [comment]
@jeffersonRibeiro
Hey how is it going with that step by step tutorial???

**Comment by criesbeck** [comment]
For my students at Northwestern, I put together a "watch me" tutorial to introduce various bits of React and Firebase Real-Time, and a "now you do it" challenge, based on the shopping cart materials and end-product. You can see them here and cannibalize as you wish:

[Quick, React! ](https://courses.cs.northwestern.edu/394/intro-react.php)-- "watch me do it"
[Learn React.](https://courses.cs.northwestern.edu/394/learn-react.php)  -- "now you do it"

**Comment by Albionjohn** [comment]
@jeffersonRibeiro Hi, is there a tutorial for this project? Would be great to have one. Thanks
