### ISSUE TITLE
Implement filters with URL params using react-routers

### ISSUE THREAD

**Issue by jeffersonRibeiro** [jeffersonRibeiro/react-shopping-cart#2]
I would like to change the url params to reflect the actual filters.

If you know how to implement that using react-router, feel free to send a PR.

**Comment by tangtangmeili** [comment]
hi ,I am so happy to meet u. And I am a fresher width React.  Recently I am using your project as my React example. Thank u very much for sharing this project. I  wanna ask you a question of that I have to command "npm run build-css" every time I update my sass.  Why not watch sass or whether did I run in the wrong way?

**Comment by jeffersonRibeiro** [comment]
Hi! great to hear :)

There's a npm script to do this, just type `npm run watch-css`

Sometimes the css build fail while watching and return an error, just save the file you are editing again and it should pass.

**Comment by tangtangmeili** [comment]
It helps me a lot. Thank u very much

**Comment by tangtangmeili** [comment]
Can I join this project?

**Comment by tangtangmeili** [comment]
Another question:
When I click the button "Add to Cart", is the process like this :  dispatch(ADD_PRODUCT)=>step in floatCartReducer and return state.  Then the state is mapped to the props through mapStateToProps.  It seems nothing to do with the function addProduct() in FloatCart.js. To be truth I do not know why I click the button "Add to Cart", the process calls the function addProduct() in FloatCart.js. I have no idea whether I express myself well.

**Comment by tangtangmeili** [comment]
I tried to commit a pull request but It seems that I have no permission. Can I join this project?
