### ISSUE TITLE
react-scripts: command not found

### ISSUE THREAD

**Issue by VishalVrk** [jeffersonRibeiro/react-shopping-cart#4]
react-shopping-cart@0.1.0 start /Users/krish/Desktop/react-shopping-cart-master
> react-scripts start

sh: react-scripts: command not found
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn
npm ERR! react-shopping-cart@0.1.0 start: `react-scripts start`
npm ERR! spawn ENOENT
npm ERR!
npm ERR! Failed at the react-shopping-cart@0.1.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/krish/.npm/_logs/2018-12-04T06_03_15_555Z-debug.log
krishs-MacBook-Pro:react-shopping-cart-master krish$

npm -v
6.4.1
node -v
v10.14.1

**Comment by jeffersonRibeiro** [comment]
Hi, thanks for the feedback!

I did a npm audit to fix some vulnerabilities and also a package cleanup,

I think it will solve your problem

**Comment by VishalVrk** [comment]
Thanks too much problem solved
