### ISSUE TITLE
react-scripts: command not found

### ISSUE THREAD

**Issue by atullohiya** [jeffersonRibeiro/react-shopping-cart#5]
PS D:\react-shopping-cart> npm install
npm WARN tar ENOENT: no such file or directory, open 'D:\react-shopping-cart\node_modules\.staging\string_decoder-f6d3fcd9\lib\string_decoder.js'
npm ERR! code E404
npm ERR! 404 Not Found: event-stream@3.3.6

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Wonder\AppData\Roaming\npm-cache\_logs\2018-12-04T06_34_24_126Z-debug.log
PS D:\react-shopping-cart> npm run server

> react-shopping-cart@0.1.0 server D:\react-shopping-cart
> nodemon server.js

'nodemon' is not recognized as an internal or external command,
operable program or batch file.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! react-shopping-cart@0.1.0 server: `nodemon server.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the react-shopping-cart@0.1.0 server script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Wonder\AppData\Roaming\npm-cache\_logs\2018-12-04T06_34_45_808Z-debug.log
PS D:\react-shopping-cart> npm start

> react-shopping-cart@0.1.0 start D:\react-shopping-cart
> react-scripts start

'react-scripts' is not recognized as an internal or external command,
operable program or batch file.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! react-shopping-cart@0.1.0 start: `react-scripts start`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the react-shopping-cart@0.1.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Wonder\AppData\Roaming\npm-cache\_logs\2018-12-04T06_36_30_836Z-debug.log

**Comment by AndyLIUMel** [comment]
I just have the same problem, I deleted the package-lock.json file in the root.
and run npm install again. Fixed.

**Comment by jeffersonRibeiro** [comment]
Hi, thanks for the feedback!

I did a npm audit to fix some vulnerabilities and also a package cleanup,

I think it will solve your problem
